### ISSUE TITLE
Will fail if it receives UTF-8 body data

### ISSUE THREAD

**Issue by jonathanstowe** [tokuhirom/p6-HTTP-Parser#4]
Hi,
I discovered that in the circumstance that e.g. HTTP::Server::Tiny receives the entire response in one chunk from the network layer, and if the HTTP body contains non-ascii data, the parse-http-request will fail while attempting to decode the whole thing as ASCII - it probably needs to check first whether the Buf contains a header separator and then only pass the actual header part.

I'll try to get to fixing this one over the weekend as it stopped me calling something a UTF-8 name :)

**Comment by jonathanstowe** [comment]
I think it is probably easiest to find the first octet in the supplied buffer that is > 127 and then only use the part of the buffer up to that point.  It doesn't seem like there's much point in doing a full scan for a header end as the parser already does that.

**Comment by zjmarlow** [comment]
In `parse-http-request`, it looks like checking for `!~~ Nil` no longer works and is consistent with the documentation.  `~~ Int ` might work?

**Comment by jonathanstowe** [comment]
This is tested in the 972bf2c7f1ea6e51c0a6de7286a03c42e42b7e0f and that appears to still work. Do you have an example failing test that demonstrates it not working?

**Comment by zjmarlow** [comment]
Sorry,  this is not the ticket it should be in.  It's failing if it does **not** receive UTF-8 data.

test 01-request-parser is failing for me with:
`Cannot resolve caller subbuf(Blob[uint8]: Int, Any); none of these signatures match:` (sigs here)
line 103 of Parser.pm6 is referenced.
